### ISSUE TITLE
Not Connecting. When will the issue resolve?

### ISSUE THREAD

**Issue by ravail121** [dougsillars/browserLiveStream#8]

**Comment by dougsillars** [comment]
This is an issue with livestream.a.video, not with the Github repo.

**Comment by ravail121** [comment]
Hi. Will you fix this issue?

**Comment by ravail121** [comment]
Oh I think you have just implemented the code. How to connect a.video?

**Comment by ravail121** [comment]
To their support or team?

**Comment by dougsillars** [comment]
One and the same.  I've replied to you on Twitter already. If you have questions, please keep to one channel for communication.
